version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  app:
    image: openjdk:17-jdk-slim
    command: [ "java", "-jar", "/app/app.jar" ]
    volumes:
      - ./target/calculate-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hello_world_schema
